#all: completion pod lib/App/AppSpec/Spec.pm
all: completion pod example

completion:
	appspec completion share/appspec-bash.yaml --zsh  > share/completion/zsh/_appspec-bash
	appspec completion share/appspec-bash.yaml --bash  > share/completion/bash/appspec-bash.bash

pod:
	appspec pod share/appspec-bash.yaml > lib/appspec-bash.pod

example: example-parser example-help example-completion

example-parser:
	perl -Ilib bin/appspec-bash generate parser examples/mydemo.yaml examples/lib/appspec

example-help:
	perl -Ilib bin/appspec-bash generate help examples/mydemo.yaml examples/lib/help

example-completion:
	appspec completion examples/mydemo.yaml --zsh  > examples/zsh/_mydemo
	appspec completion examples/mydemo.yaml --bash  > examples/bash/mydemo.bash

example-pod:
	appspec pod examples/mydemo.yaml > examples/pod/mydemo.pod

#lib/App/AppSpec/Spec.pm: share/appspec-bash.yaml
#	perl tools/generate-spec-pm.pl
