#!/bin/bash

# Generated by perl modules
# App::Spec v0.010
# App::Spec::Bash v0.000

APPSPEC.help() {
  cat <<EOHELP
Usage
EOHELP
}
APPSPEC._meta() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo _meta <subcommands> [options]

Subcommands:
completion  Shell completion functions
pod         Pod documentation

Options:
--help -h            Show command help (flag)
--version -V         Show version (flag)

EOHELP
}

APPSPEC._meta-completion() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo _meta completion <subcommands> [options]

Subcommands:
generate  Generate self completion

Options:
--help -h            Show command help (flag)
--version -V         Show version (flag)

EOHELP
}

APPSPEC._meta-completion-generate() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo _meta completion generate [options]


Options:
--bash               for bash (flag)
--help -h            Show command help (flag)
--name               name of the program (optional, override name in spec)
--version -V         Show version (flag)
--zsh                for zsh (flag)

EOHELP
}

APPSPEC._meta-pod() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo _meta pod <subcommands> [options]

Subcommands:
generate  Generate self pod

Options:
--help -h            Show command help (flag)
--version -V         Show version (flag)

EOHELP
}

APPSPEC._meta-pod-generate() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo _meta pod generate [options]


Options:
--help -h            Show command help (flag)
--version -V         Show version (flag)

EOHELP
}

APPSPEC.help() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo help <subcommands> [options]

Subcommands:
_meta    
nested1  
test1    

Options:
--all                 (flag)
--help -h            Show command help (flag)
--version -V         Show version (flag)

EOHELP
}

APPSPEC.help-_meta() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo help _meta <subcommands> [options]

Subcommands:
completion  
pod         

Options:
--all                 (flag)
--help -h            Show command help (flag)
--version -V         Show version (flag)

EOHELP
}

APPSPEC.help-_meta-completion() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo help _meta completion <subcommands> [options]

Subcommands:
generate  

Options:
--all                 (flag)
--help -h            Show command help (flag)
--version -V         Show version (flag)

EOHELP
}

APPSPEC.help-_meta-completion-generate() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo help _meta completion generate [options]


Options:
--all                 (flag)
--help -h            Show command help (flag)
--version -V         Show version (flag)

EOHELP
}

APPSPEC.help-_meta-pod() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo help _meta pod <subcommands> [options]

Subcommands:
generate  

Options:
--all                 (flag)
--help -h            Show command help (flag)
--version -V         Show version (flag)

EOHELP
}

APPSPEC.help-_meta-pod-generate() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo help _meta pod generate [options]


Options:
--all                 (flag)
--help -h            Show command help (flag)
--version -V         Show version (flag)

EOHELP
}

APPSPEC.help-nested1() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo help nested1 <subcommands> [options]

Subcommands:
nested2  

Options:
--all                 (flag)
--help -h            Show command help (flag)
--version -V         Show version (flag)

EOHELP
}

APPSPEC.help-nested1-nested2() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo help nested1 nested2 [options]


Options:
--all                 (flag)
--help -h            Show command help (flag)
--version -V         Show version (flag)

EOHELP
}

APPSPEC.help-test1() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo help test1 [options]


Options:
--all                 (flag)
--help -h            Show command help (flag)
--version -V         Show version (flag)

EOHELP
}

APPSPEC.nested1() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo nested1 <subcommands> [options]

Subcommands:
nested2  Nested subcommand 2

Options:
--help -h            Show command help (flag)
--version -V         Show version (flag)

EOHELP
}

APPSPEC.nested1-nested2() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo nested1 nested2 [options]


Options:
--help -h            Show command help (flag)
--version -V         Show version (flag)

EOHELP
}

APPSPEC.test1() {
  cat <<EOHELP
mydemo - Demo
Demonstrate appspec for bash

Usage: mydemo test1 [options]


Options:
--flag-a -a          Flag a (flag)
--flag-b -b          Flag b (flag)
--flag-c -c      []  Flag c (incremental) (flag; multiple)
--help -h            Show command help (flag)
--test-d -d          Option d
--test-e -e          Option e
--test-f -f      []  Option f (multi) (multiple)
--test-g -g   *      Option g (required)
--version -V         Show version (flag)

EOHELP
}



